package info.pilnujemy.uph.magazines.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public class FakeData {

	public static final List<Magazine> LIST_OF_MAGAZINES;
	static{
		ArrayList<Magazine> list = new ArrayList<>(200);
		list.add(new Magazine("Codziennik feministyczny", 7, 1987));
		list.add(new Magazine("Furia", 1, 1986));
		list.add(new Magazine("Furia", 5, 1995));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 7, 1995));
		list.add(new Magazine("Codziennik feministyczny", 7, 1989));
		list.add(new Magazine("FEMKA", 5, 2001));
		list.add(new Magazine("Zadra", 7, 1996));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 9, 1999));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1990));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 7, 2000));
		list.add(new Magazine("FEMKA", 3, 1987));
		list.add(new Magazine("Furia", 7, 1985));
		list.add(new Magazine("ROMANO ATMO", 3, 1994));
		list.add(new Magazine("FEMKA", 9, 1982));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 1, 1982));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 1989));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 1986));
		list.add(new Magazine("Furia", 5, 1998));
		list.add(new Magazine("Zadra", 3, 2003));
		list.add(new Magazine("PANOPTIKUM", 7, 2004));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 9, 2003));
		list.add(new Magazine("Codziennik feministyczny", 7, 1982));
		list.add(new Magazine("FEMKA", 7, 1990));
		list.add(new Magazine("FEMKA", 3, 1996));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 5, 1994));
		list.add(new Magazine("KOBIETA I BIZNES", 7, 1983));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 1988));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 9, 1983));
		list.add(new Magazine("Zadra", 5, 2003));
		list.add(new Magazine("PANOPTIKUM", 7, 1996));
		list.add(new Magazine("Zadra", 1, 2002));
		list.add(new Magazine("Dialog Pheniben", 7, 2002));
		list.add(new Magazine("FEMKA", 5, 1999));
		list.add(new Magazine("Dialog Pheniben", 3, 1983));
		list.add(new Magazine("FEMKA", 1, 1983));
		list.add(new Magazine("PANOPTIKUM", 5, 1991));
		list.add(new Magazine("PANOPTIKUM", 3, 2002));
		list.add(new Magazine("ROMANO ATMO", 5, 1998));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1990));
		list.add(new Magazine("ROMANO ATMO", 1, 1995));
		list.add(new Magazine("FEMKA", 7, 1986));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 1990));
		list.add(new Magazine("Dialog Pheniben", 7, 1987));
		list.add(new Magazine("Dialog Pheniben", 9, 1988));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 5, 1993));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1990));
		list.add(new Magazine("PANOPTIKUM", 7, 2004));
		list.add(new Magazine("Dialog Pheniben", 1, 1986));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1997));
		list.add(new Magazine("Zadra", 5, 1990));
		list.add(new Magazine("FEMKA", 1, 1984));
		list.add(new Magazine("BARWY ŻYWCA", 3, 2003));
		list.add(new Magazine("PANOPTIKUM", 3, 1991));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1987));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 1999));
		list.add(new Magazine("Dialog Pheniben", 5, 1999));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 1981));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 3, 1982));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1983));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 9, 1991));
		list.add(new Magazine("FEMKA", 1, 1984));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1987));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 2004));
		list.add(new Magazine("Dialog Pheniben", 1, 1999));
		list.add(new Magazine("Zadra", 9, 2004));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 7, 2003));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 1981));
		list.add(new Magazine("ROMANO ATMO", 1, 2004));
		list.add(new Magazine("Zadra", 1, 1987));
		list.add(new Magazine("Furia", 7, 1998));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1985));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 1, 2001));
		list.add(new Magazine("FEMKA", 5, 1982));
		list.add(new Magazine("BARWY ŻYWCA", 1, 2004));
		list.add(new Magazine("Zadra", 5, 1994));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 1982));
		list.add(new Magazine("BARWY ŻYWCA", 1, 1996));
		list.add(new Magazine("Furia", 1, 1982));
		list.add(new Magazine("BARWY ŻYWCA", 5, 1986));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 2003));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 7, 2001));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 5, 1996));
		list.add(new Magazine("Codziennik feministyczny", 1, 1981));
		list.add(new Magazine("KOBIETA I BIZNES", 7, 1986));
		list.add(new Magazine("FEMKA", 3, 1995));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 2001));
		list.add(new Magazine("PANOPTIKUM", 3, 1991));
		list.add(new Magazine("PANOPTIKUM", 9, 1998));
		list.add(new Magazine("KOBIETA I BIZNES", 5, 1986));
		list.add(new Magazine("Furia", 7, 1985));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 7, 1987));
		list.add(new Magazine("BARWY ŻYWCA", 5, 1997));
		list.add(new Magazine("Furia", 7, 2002));
		list.add(new Magazine("Furia", 1, 1988));
		list.add(new Magazine("PANOPTIKUM", 9, 1991));
		list.add(new Magazine("FEMKA", 5, 2005));
		list.add(new Magazine("ROMANO ATMO", 3, 1996));
		list.add(new Magazine("PANOPTIKUM", 9, 1989));
		list.add(new Magazine("FEMKA", 3, 1982));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 7, 2003));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 1996));
		list.add(new Magazine("Codziennik feministyczny", 5, 1982));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 3, 1987));
		list.add(new Magazine("Dialog Pheniben", 7, 1996));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 1, 2003));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 2003));
		list.add(new Magazine("BARWY ŻYWCA", 3, 1985));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1990));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 7, 1984));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1985));
		list.add(new Magazine("BARWY ŻYWCA", 5, 1991));
		list.add(new Magazine("PANOPTIKUM", 3, 1993));
		list.add(new Magazine("KOBIETA I BIZNES", 9, 1988));
		list.add(new Magazine("ROMANO ATMO", 3, 1991));
		list.add(new Magazine("PANOPTIKUM", 3, 2003));
		list.add(new Magazine("Furia", 5, 1981));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 9, 1994));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 7, 1989));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 9, 1983));
		list.add(new Magazine("PANOPTIKUM", 3, 1986));
		list.add(new Magazine("ROMANO ATMO", 5, 1985));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 1981));
		list.add(new Magazine("Dialog Pheniben", 5, 1984));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 3, 1998));
		list.add(new Magazine("Zadra", 9, 1992));
		list.add(new Magazine("KOBIETA I BIZNES", 1, 2004));
		list.add(new Magazine("Zadra", 7, 1995));
		list.add(new Magazine("FEMKA", 9, 1999));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 3, 2001));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 1986));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 7, 1997));
		list.add(new Magazine("ROMANO ATMO", 5, 1983));
		list.add(new Magazine("ROMANO ATMO", 1, 1992));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 7, 1981));
		list.add(new Magazine("FEMKA", 7, 1981));
		list.add(new Magazine("Codziennik feministyczny", 1, 2002));
		list.add(new Magazine("Codziennik feministyczny", 3, 2001));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 1990));
		list.add(new Magazine("Codziennik feministyczny", 1, 1990));
		list.add(new Magazine("Codziennik feministyczny", 7, 1991));
		list.add(new Magazine("KOBIETA I BIZNES", 3, 2004));
		list.add(new Magazine("Furia", 9, 2001));
		list.add(new Magazine("BARWY ŻYWCA", 9, 1981));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 3, 1992));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 5, 1984));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 3, 2003));
		list.add(new Magazine("ROMANO ATMO", 1, 1986));
		list.add(new Magazine("Zadra", 5, 1988));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 3, 1983));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 7, 1984));
		list.add(new Magazine("ROMANO ATMO", 5, 1983));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 3, 1997));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 9, 1993));
		list.add(new Magazine("Dialog Pheniben", 3, 1994));
		list.add(new Magazine("Dialog Pheniben", 5, 1987));
		list.add(new Magazine("Codziennik feministyczny", 5, 2000));
		list.add(new Magazine("Codziennik feministyczny", 1, 1999));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 5, 2005));
		list.add(new Magazine("KOBIETA I BIZNES", 7, 2000));
		list.add(new Magazine("Codziennik feministyczny", 1, 1990));
		list.add(new Magazine("BARWY ŻYWCA", 1, 2004));
		list.add(new Magazine("KOBIETA I BIZNES", 5, 2003));
		list.add(new Magazine("Zadra", 9, 1991));
		list.add(new Magazine("PANOPTIKUM", 3, 2004));
		list.add(new Magazine("Furia", 9, 1998));
		list.add(new Magazine("BARWY ŻYWCA", 3, 1987));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 7, 1990));
		list.add(new Magazine("Furia", 3, 2003));
		list.add(new Magazine("Zadra", 3, 2001));
		list.add(new Magazine("Zadra", 5, 1981));
		list.add(new Magazine("PANOPTIKUM", 3, 2001));
		list.add(new Magazine("BARWY ŻYWCA", 1, 1981));
		list.add(new Magazine("Dialog Pheniben", 9, 1996));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 3, 2001));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 1, 2001));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 5, 1986));
		list.add(new Magazine("Furia", 3, 2004));
		list.add(new Magazine("KOBIETA I BIZNES", 5, 1981));
		list.add(new Magazine("BARWY ŻYWCA", 5, 2000));
		list.add(new Magazine("Dialog Pheniben", 9, 2003));
		list.add(new Magazine("Furia", 3, 1995));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 1, 1989));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 9, 1998));
		list.add(new Magazine("Niepełnosprawność - zagadnienia, problemy, rozwiązania", 7, 1984));
		list.add(new Magazine("Furia", 1, 1989));
		list.add(new Magazine("Furia", 3, 2005));
		list.add(new Magazine("Dialog Pheniben", 1, 1997));
		list.add(new Magazine("Replika - dwumiesięcznik społeczno-kulturalny LGBTQ", 7, 1993));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 1, 1989));
		list.add(new Magazine("KOBIETA I BIZNES", 9, 1987));
		list.add(new Magazine("BARWY ŻYWCA", 3, 2001));
		list.add(new Magazine("PANOPTIKUM", 7, 2003));
		list.add(new Magazine("Furia", 3, 1986));
		list.add(new Magazine("KOBIETA I BIZNES", 9, 1998));
		list.add(new Magazine("KWARTALNIK O PRAWACH CZŁOWIEKA", 7, 1991));
		list.add(new Magazine("Magazyn NIGDY WIĘCEJ", 7, 1994));
		list.add(new Magazine("Dialog Pheniben", 7, 1988));
		list.add(new Magazine("KOBIETA I BIZNES", 7, 2002));
		list.add(new Magazine("Zadra", 9, 1984));
		list.add(new Magazine("Furia", 3, 1984));
		LIST_OF_MAGAZINES = Collections.unmodifiableList(list);
	}
}
